config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :items do
  	member do
  		patch :complete
  	end
  end
  root 'items#index'
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :user

	def completed?
		!completed_at.blank?
	end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :items
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
	before_action :find_item, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index]

	def index

		if user_signed_in?
		
			@items = Item.where(:user_id => current_user.id).order("created_at DESC")

		end	
	end

	def show
	end

	def new
		@item = current_user.items.build
	end

	def create
		@item = current_user.items.build(item_params)

		if @item.save
			redirect_to root_path
		else
			render 'new'
		end
	end

	def edit
	end

	def update

		if @item.update(item_params)
	
			redirect_to root_path, notice: "Дело успено изенено !"

		else
			render 'edit'
		end
	end

	def destroy
		@item.destroy
		redirect_to root_path , notice: "Удалено!"
	end

	def complete
		@item = Item.find(params[:id])
		@item.update_attribute(:completed_at, Time.now)
		redirect_to root_path, notice: "Дело успешно выполнено!"

	end

	private
		def item_params
			params.require(:item).permit(:title, :description)
		end

		def find_item
			@item = Item.find(params[:id])
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>
	<%= f.input :title, label: "Название" %>
	<%= f.input :description, label: "Описание"%>
	<%= f.button :submit, "Создать" , :class => "btn-custom,a"%>
<% end %>

app/views/items/_static_landing_page.html.erb
<div class="jumbotron">
	<h2>Добро пожаловать!</h2>
	<h3>Поможем тебе слелить за делами.</h3>
	<%= link_to "Регистрация", new_user_registration_path, class: "btn btn-primary" %>
	<%= link_to "Вход", new_user_session_path, class: "btn btn-primary" %>
</div>

app/views/items/edit.html.erb
<div class="kk col-md-6 col-md-offset-3">
	<h1>Изменить дело</h1>

	<%= render 'form' %>
</div>

app/views/items/index.html.erb
<!-- Checks to see if a user is signed in, if one is, it will list its checklist. -->
<!-- If not, it will render the landing page that asks the user to sign up or login. -->

<div class="col-md-offset-3">
		
<%= content_tag :div, "", id: "items_chart", data: {items: @items} %>

			<h1 ><span style="color: #9FFF0A;font-family: 'Oswald'; font-size: 2em">To Do</span>'шка сроком в <span style="font-family: 'Oswald', sans-serif; color:#FB302F; font-size: 2em"> 2 </span>часа</h1>
		</div>

</div>

<% if user_signed_in? %>
	<div class="col-md-6 col-md-offset-3">
		<% @items.each do |item| %>
			<div class="index-wrapper">
				<% if item.completed? %>
					<div class="row item">
						<div class="col-md-8">
							<h2 style="opacity: 0.8;" class="item-title"><strike><%= item.title %></strike></h2>
							<!-- <h2 style="opacity: 0.5;" class="item-title"><strike><%= link_to item.title, item %></strike></h2> -->
							<p style="opacity: 0.8;" class="item-sub-title item-desc input-field1"><%= item.description %></p>
							<p style="opacity: 0.8;" 
							
							class="time-created-at item-sub-title">Выполнено <%= time_ago_in_words(item.completed_at) %> назад</p>
						</div>
						<div class="col-md-2">
						
						</div>
						<div class="col-md-2">
							<p><%= link_to item, method: :delete, data: { confirm: "Вы уверены?" } do %></p>
								<i class="fa fa-trash fa-lg"></i>
							<% end %>
						</div>	
					</div>
				<% else %>	
					<div class="row item">
						<div class="col-md-8">
							<h2 class="item-title"><%= link_to item.title, item %></h2>
							<p class="item-sub-title item-desc input-field1"><%= item.description %></p>
							<p style="opacity: 0.8;" class="time-created-at item-sub-title">Создана <%= time_ago_in_words(item.created_at) %> назад</p> 
						
						<% a = time_ago_in_words(item.created_at).to_s.split(' ')%>
						<!-- 	условие проверки на просроченность -->
					

						<%if  a.include? ('minutes') or a.include? ('minute') or a.include? ('about') or a.include? ('days')%>
						<h4 style=" font-family: 'Oswald', sans-serif;font-size: 1.5em; color:##8120A6">В ожидании выполнения</h4>
						<% end %>


						<%if  a.include? "hours" %>
						
						<% q =  a.find{|a| a.size<3}; f = q.to_i -  2 %>
					

								<% if (f.to_i == 0) %> <!-- 1 час -->
						<h4 style=" font-family: 'Oswald', sans-serif;font-size: 1.5em; color:#FB302F">Срок выполнения просрочен, приступите к выполнению</h4>
								<% end %>

								<% if (f.to_i == 1) %> <!-- 1 час -->
						<h4 style=" font-family: 'Oswald', sans-serif;font-size: 1.5em; color:#FB302F">Срок выполнения просрочен <%= f %> час назад</h4>
								<% end %>
								
								<% if (f.to_i < 5 and f.to_i > 1 ) %> <!-- 2-4 часа -->
						<h4 style=" font-family: 'Oswald', sans-serif;font-size: 1.5em; color:#FB302F">Срок выполнения просрочен <%= f %> часа назад</h4>
								<% end%>
								<!-- 5 часов -->
								<% if (f.to_i > 4) %>
						<h4 style=" font-family: 'Oswald', sans-serif;font-size: 1.5em; color:#FB302F">Срок выполнения просрочен <%= f %> часов назад</h4>
								<% end %>
						<% end %>

						<%if  a.include? ("days") or a.include? ("day") %>
						
							<% q =  a.find{|a| a.size<3}; f = q.to_i%>
								<% if (f.to_i == 1) %> <!-- 1 день -->
						<h4 style=" font-family: 'Oswald', sans-serif;font-size: 1.5em; color:#FB302F">Срок выполнения просрочен <%= f %> день назад</h4>
								<% elsif (f.to_i < 5) %> <!-- 2-4 день -->
						<h4 style=" font-family: 'Oswald', sans-serif;font-size: 1.5em; color:#FB302F">Срок выполнения просрочен <%= f %> дня назад</h4>
							<% else %> 	
							<!-- 5 дней -->

						<h4 style=" font-family: 'Oswald', sans-serif;font-size: 1.5em; color:#FB302F">Срок выполнения просрочен <%= f %> дней назад</h4>
								<% end %>
						<% end %>

						</div>
						
						<div class="col-md-2">
							<p><%= link_to complete_item_path(item), method: :patch do %></p>
								<i class="fa fa-check fa-lg"></i>
							<% end %>
						</div>


						<div class="col-md-2">
							<p><%= link_to item, method: :delete, data: { confirm: "Вы уверены?" } do %></p>
								<i class="fa fa-trash fa-lg"></i>
							<% end %>
						</div>
					</div>
				<% end %>
			</div>

		<% end %>	
	</div>
<% else %>
	<%= render 'static_landing_page' %>
<% end %>	

app/views/items/new.html.erb
<div class="kk col-md-6 col-md-offset-3">
	<h1>Новое дело</h1>

	<%= render 'form'  %>
</div>

app/views/items/show.html.erb
<div class="kk col-md-6 col-md-offset-3">
	<h2><%= @item.title %></h2>
	<p class = "input-field1"><%= @item.description %></p>

	<%= link_to "Изменить", edit_item_path(@item), class: "btn-custom" %>
	<%= link_to "Удалить", item_path(@item), method: :delete, data: { confirm: "Вы уверены?" }, class: "btn-custom" %>
	<%= link_to "Назад", root_path , class: "btn-custom"%>
	
</div>

app/views/layouts/application.html.erb
<!-- Checks to see if a user is signed in, if one is, it will list its checklist. -->
<!-- If not, it will render the landing page that asks the user to sign up or login. -->

<div class="col-md-offset-3">
		
<%= content_tag :div, "", id: "items_chart", data: {items: @items} %>

			<h1 ><span style="color: #9FFF0A;font-family: 'Oswald'; font-size: 2em">To Do</span>'шка сроком в <span style="font-family: 'Oswald', sans-serif; color:#FB302F; font-size: 2em"> 2 </span>часа</h1>
		</div>

</div>

<% if user_signed_in? %>
	<div class="col-md-6 col-md-offset-3">
		<% @items.each do |item| %>
			<div class="index-wrapper">
				<% if item.completed? %>
					<div class="row item">
						<div class="col-md-8">
							<h2 style="opacity: 0.8;" class="item-title"><strike><%= item.title %></strike></h2>
							<!-- <h2 style="opacity: 0.5;" class="item-title"><strike><%= link_to item.title, item %></strike></h2> -->
							<p style="opacity: 0.8;" class="item-sub-title item-desc input-field1"><%= item.description %></p>
							<p style="opacity: 0.8;" 
							
							class="time-created-at item-sub-title">Выполнено <%= time_ago_in_words(item.completed_at) %> назад</p>
						</div>
						<div class="col-md-2">
						
						</div>
						<div class="col-md-2">
							<p><%= link_to item, method: :delete, data: { confirm: "Вы уверены?" } do %></p>
								<i class="fa fa-trash fa-lg"></i>
							<% end %>
						</div>	
					</div>
				<% else %>	
					<div class="row item">
						<div class="col-md-8">
							<h2 class="item-title"><%= link_to item.title, item %></h2>
							<p class="item-sub-title item-desc input-field1"><%= item.description %></p>
							<p style="opacity: 0.8;" class="time-created-at item-sub-title">Создана <%= time_ago_in_words(item.created_at) %> назад</p> 
						
						<% a = time_ago_in_words(item.created_at).to_s.split(' ')%>
						<!-- 	условие проверки на просроченность -->
						<%= p a%>

						<%if  a.include? ('minutes') or a.include? ('minute') or a.include? ('about') or a.include? ('days')%>
						<h4 style=" font-family: 'Oswald', sans-serif;font-size: 1.5em; color:##8120A6">В ожидании выполнения</h4>
						<% end %>


						<%if  a.include? "hours" %>
						
						<% q =  a.find{|a| a.size<3}; f = q.to_i -  2 %>
					

								<% if (f.to_i == 0) %> <!-- 1 час -->
						<h4 style=" font-family: 'Oswald', sans-serif;font-size: 1.5em; color:#FB302F">Срок выполнения просрочен, приступите к выполнению</h4>
								<% end %>

								<% if (f.to_i == 1) %> <!-- 1 час -->
						<h4 style=" font-family: 'Oswald', sans-serif;font-size: 1.5em; color:#FB302F">Срок выполнения просрочен <%= f %> час назад</h4>
								<% end %>
								
								<% if (f.to_i < 5 and f.to_i > 1 ) %> <!-- 2-4 часа -->
						<h4 style=" font-family: 'Oswald', sans-serif;font-size: 1.5em; color:#FB302F">Срок выполнения просрочен <%= f %> часа назад</h4>
								<% end%>
								<!-- 5 часов -->
								<% if (f.to_i > 4) %>
						<h4 style=" font-family: 'Oswald', sans-serif;font-size: 1.5em; color:#FB302F">Срок выполнения просрочен <%= f %> часов назад</h4>
								<% end %>
						<% end %>

						<%if  a.include? ("days") or a.include? ("day") %>
						
							<% q =  a.find{|a| a.size<3}; f = q.to_i%>
								<% if (f.to_i == 1) %> <!-- 1 день -->
						<h4 style=" font-family: 'Oswald', sans-serif;font-size: 1.5em; color:#FB302F">Срок выполнения просрочен <%= f %> день назад</h4>
								<% elsif (f.to_i < 5) %> <!-- 2-4 день -->
						<h4 style=" font-family: 'Oswald', sans-serif;font-size: 1.5em; color:#FB302F">Срок выполнения просрочен <%= f %> дня назад</h4>
							<% else %> 	
							<!-- 5 дней -->

						<h4 style=" font-family: 'Oswald', sans-serif;font-size: 1.5em; color:#FB302F">Срок выполнения просрочен <%= f %> дней назад</h4>
								<% end %>
						<% end %>

						</div>
						
						<div class="col-md-2">
							<p><%= link_to complete_item_path(item), method: :patch do %></p>
								<i class="fa fa-check fa-lg"></i>
							<% end %>
						</div>


						<div class="col-md-2">
							<p><%= link_to item, method: :delete, data: { confirm: "Вы уверены?" } do %></p>
								<i class="fa fa-trash fa-lg"></i>
							<% end %>
						</div>
					</div>
				<% end %>
			</div>

		<% end %>	
	</div>
<% else %>
	<%= render 'static_landing_page' %>
<% end %>	